import type { InvoicePreviewData } from "@/types/invoice-template";

export const PREVIEW_INVOICE: InvoicePreviewData = {
  invoiceTitle: "Tax Invoice",
  invoiceNumber: "BS-2408",
  invoiceDate: "Mar 08, 2026",
  dueDate: "Mar 22, 2026",
  placeOfSupply: "Maharashtra",
  taxMode: "CGST_SGST",
  watermarkText: "BillSutra",
  business: {
    businessName: "BillSutra Studio",
    address: "208, Riverwalk Avenue, Pune, Maharashtra - 411001",
    businessAddress: {
      addressLine1: "208, Riverwalk Avenue",
      city: "Pune",
      state: "Maharashtra",
      pincode: "411001",
    },
    phone: "+91 98765 43210",
    email: "hello@billsutra.app",
    website: "www.billsutra.app",
    logoUrl: "",
    taxId: "27AAEPM4567G1Z9",
    currency: "INR",
    showLogoOnInvoice: true,
    showTaxNumber: true,
    showPaymentQr: true,
  },
  client: {
    name: "Kalpana Textiles",
    type: "business",
    gstin: "27AACCK1234A1Z2",
    email: "accounts@kalpana.com",
    phone: "+91 99887 12210",
    address: "7, MG Road, Mumbai, Maharashtra - 400001",
  },
  items: [
    {
      name: "Inventory subscription",
      description: "Monthly plan",
      hsnSac: "9983",
      quantity: 1,
      unitPrice: 1200,
      taxRate: 18,
      amount: 1416,
    },
    {
      name: "Custom onboarding",
      description: "One-time setup",
      hsnSac: "9983",
      quantity: 1,
      unitPrice: 3500,
      taxRate: 18,
      amount: 4130,
    },
    {
      name: "Barcode labels",
      description: "Thermal sticker roll",
      hsnSac: "4821",
      quantity: 4,
      unitPrice: 150,
      taxRate: 12,
      amount: 672,
    },
  ],
  totals: {
    subtotal: 5300,
    tax: 918,
    discount: 0,
    total: 6218,
    cgst: 459,
    sgst: 459,
    roundOff: 0,
  },
  notes: "Thanks for choosing BillSutra. Payment due within 14 days.",
  paymentInfo: "UPI: billsutra@upi | Bank: HDFC Bank | A/C: 50200012345678 | IFSC: HDFC0000123",
  payment: {
    mode: "UPI",
    upiId: "billsutra@upi",
    bankName: "HDFC Bank",
    accountName: "BillSutra Studio",
    accountNumber: "50200012345678",
    ifsc: "HDFC0000123",
  },
};
